export default {
  SESSION_MAGIC_ID: '23818bf4-a8ec-4ddc-8928-a126beff0ca6',

  ERROR_NOOP: 'ERROR_NOOP',

  ERROR_WX_BUTTON_GET_USER_INFO_FAILED: 'ERROR_WX_BUTTON_GET_USER_INFO_FAILED',
  ERROR_WX_LOGIN_FAILED: 'ERROR_WX_LOGIN_FAILED',
  ERROR_WX_GET_USER_INFO_FAILED: 'ERROR_WX_GET_USER_INFO_FAILED',
  ERROR_WX_REQUEST_FAILED: 'ERROR_WX_REQUEST_FAILED',

  ERROR_CREATE_SESSION_REQUEST_FAILED: 'ERROR_CREATE_SESSION_REQUEST_FAILED',
  ERROR_CREATE_SESSION_FAILED: 'ERROR_CREATE_SESSION_FAILED',
  ERROR_UPDATE_SESSION_REQUEST_FAILED: 'ERROR_UPDATE_SESSION_REQUEST_FAILED',
  ERROR_UPDATE_SESSION_FAILED: 'ERROR_UPDATE_SESSION_FAILED',

  ERROR_REQUEST_AUTH_ERROR: 'ERROR_REQUEST_AUTH_ERROR',
  ERROR_REQUEST_CLIENT_ERROR: 'ERROR_REQUEST_CLIENT_ERROR',
  ERROR_REQUEST_REDIRECT_ERROR: 'ERROR_REQUEST_REDIRECT_ERROR',
  ERROR_REQUEST_SERVER_ERROR: 'ERROR_REQUEST_SERVER_ERROR',
  ERROR_REQUEST_UNKNOWN_ERROR: 'ERROR_REQUEST_UNKNOWN_ERROR'
};
